query Categories {
  forumCategories {
    id
    title
    description
    slug
    created_at
    updated_at

    subcategories {
      id
      title
      slug
      created_at
      updated_at
      postCount

      posts {
        commentCount
      }
    }
  }
}