query Subcategory($slug: String!) {
  subcategory: forumSubcategoryBySlug(slug: $slug) {
    id
    title
    slug

    posts {
      id
      title
      pinned
      slug
      commentCount

      author: user {
        id
        first_name
        last_name
        email
      }

      comments {
        id
        created_at
        updated_at

        author: user {
          id
          first_name
          last_name
          email
        }
      }
    }
  }
}