query Friend($id: ID!) {
  friend: user(id: $id) {
    id
    avatar_url
    country
    created_at
    email
    first_name
    last_name
    pending_invite
    subscription_level
    trail_name
    updated_at

    packs {
      id
      name
      user_id
      active
      theme
      created_at
      updated_at
    }

    trips {
      id
      name
      description
      owner_id
      pack_id
      starting_point
      ending_point
      created_at
      updated_at
    }
  }
}