<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::insert([
            [
                'email' => 'benny.timkins@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Benny',
                'last_name' => 'Timkins',
                'trail_name' => 'Walk and Eat',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'annual',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'michael.scott@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Michael',
                'last_name' => 'Scott',
                'trail_name' => 'Boss',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'free',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'pam.beasley@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Pam',
                'last_name' => 'Beasley',
                'trail_name' => 'Artsy Fartsy',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'monthly',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'dwight.schrute@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Dwight',
                'last_name' => 'Schrute',
                'trail_name' => 'Recyclops',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'free',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'jim.halpert@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Jim',
                'last_name' => 'Halpert',
                'trail_name' => 'Big Tuna',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'annual',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'holly.flax@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Holly',
                'last_name' => 'Flax',
                'trail_name' => 'HR',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'annual',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'oscar.nunez@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Oscar',
                'last_name' => 'Nunez',
                'trail_name' => 'Well Actually',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'annual',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'andy.bernard@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Andy',
                'last_name' => 'Bernard',
                'trail_name' => 'Temper Tantrum',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'free',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'email' => 'toby.flenderson@gmail.com',
                'email_verified_at' => \Carbon\Carbon::now(),
                'avatar_url' => null,
                'first_name' => 'Toby',
                'last_name' => 'Flenderson',
                'trail_name' => 'The Worst',
                'address_1' => '123 Main St',
                'address_2' => '',
                'city' => 'Bellevue',
                'state' => 'WA',
                'country' => 'United States',
                'subscription_level' => 'free',
                'measuring_system' => 'Imperial',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
        ]);
    }
}
