query Categories($pack_id:ID!) {
  categories(pack_id:$pack_id) {
    id
    name
    unit
    created_at
    updated_at

    items(orderBy: [{ columns: "position", order: ASC }]) {
      id
      name
      weight
      unit
      price
      position
      generic_type
      consumable
      worn
      quantity
      created_at
      updated_at
    }
  }
}