query Packs {
  packs {
    id
    name
    active
    created_at
    updated_at

    categories {
      id
      name
      created_at
      updated_at

      categories_items {
        id
        position
        created_at
        updated_at

        item {
          id
          name
          weight
          price
          generic_type
          consumable
          worn
          created_at
          updated_at
        }
      }
    }
  }
}