query Packs {
  packs {
    id
    name
    active
    theme
    created_at
    updated_at

    categories {
      id
      name
      unit
      pack_id
      created_at
      updated_at

      items(orderBy: [{ columns: "position", order: ASC }]) {
        id
        name
        weight
        unit
        price
        position
        generic_type
        consumable
        worn
        quantity
        category_id
        created_at
        updated_at
      }
    }
  }
}