query Trips {
  trips {
    id
    name
    description
    starting_point
    ending_point
    owner_id

    owner {
      id
      email
      first_name
      last_name
      trail_name
    }

    todos {
      id
      title
      checked
      created_at
      updated_at
    }

    shoppingListItems {
      id
      title
      checked
      quantity
      created_at
      updated_at
    }

    tripDetails {
			id
			title
			url
			value
			type
			created_at
			updated_at
    }

    friends: users {
      id
      avatar_url
      first_name
      last_name
      trail_name
      email
      pending_invite
    }

    pack {
      id
      name
      active
      created_at
      updated_at

      categories {
        id
        name
        created_at
        updated_at

        items(orderBy: [{ columns: "position", order: ASC }]) {
          id
          name
          weight
          price
          position
          generic_type
          consumable
          worn
          quantity
          created_at
          updated_at
        }
      }
    }
  }
}